# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-04 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(max_length=240)),
                ('booking_start_date', models.DateTimeField(auto_now_add=True)),
                ('booking_end_date', models.DateTimeField(blank=True, null=True)),
                ('rental_price', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=16, unique=True)),
                ('model_year', models.DateField()),
                ('car_name', models.CharField(max_length=40)),
                ('car_image', models.ImageField(blank=True, upload_to='cars')),
                ('description', models.CharField(max_length=200)),
                ('is_available_car', models.BooleanField(default=False)),
                ('car_price', models.IntegerField()),
                ('power_hp', models.CharField(blank=True, max_length=20)),
                ('transmission', models.CharField(choices=[('Auto', 'Auto'), ('Manual', 'Manual')], max_length=10)),
                ('seats', models.CharField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('air_bags', models.CharField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('car_image_internal', models.ImageField(blank=True, upload_to='cars')),
                ('car_image_internal2', models.ImageField(blank=True, upload_to='cars')),
                ('fuel_type', models.CharField(choices=[('Petrol', 'PETROL'), ('Diesel', 'Diesel'), ('Gas', 'Gas')], max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buggy_app.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('hex', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('customer_age', models.IntegerField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('license_year', models.IntegerField()),
                ('tlc_number', models.IntegerField()),
                ('contact_num', models.IntegerField()),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.TimeField(blank=True)),
                ('time_check', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buggy_app.Color'),
        ),
        migrations.AddField(
            model_name='car',
            name='times_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buggy_app.Times'),
        ),
        migrations.AddField(
            model_name='booking',
            name='book_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_car', to='buggy_app.Car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_customers', to='buggy_app.Customer'),
        ),
    ]
